name: Generate Sitemap

on:
  push:
    branches: [ main ]

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate sitemap.xml
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://mahavirvora.github.io/

      - name: Commit sitemap if updated
        run: |
          if [[ `git status --porcelain sitemap.xml` ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email '41898282+github‑actions[bot]@users.noreply.github.com'
            git add sitemap.xml
            git commit -m "chore: update sitemap.xml"
            git push
          fi
