name: Sync to voramahavir.github.io

on:
  push:
    branches:
      - main
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Push to target repository
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.TARGET_REPO_TOKEN }}
          repository: voramahavir/voramahavir.github.io
          branch: master
